import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import test from "node:test";
import assert from "node:assert/strict";
import messages from "../messages/en.json" with { type: "json" };

const require = createRequire(import.meta.url);
const ts = require("typescript");

const sourceRoots = ["app", "components", "lib", "scripts"];
const sourceExtensions = new Set([".tsx", ".ts", ".mjs"]);
const skippedSegments = new Set(["generated"]);
const technicalLiteralAllowlist = new Set([
  "use client",
  "AUTO-GENERATED FILE. DO NOT EDIT.",
  "Generated by scripts/generate-settings-docs.mjs",
  "return input;",
  "return options;",
  "(prefers-color-scheme: dark)",
]);
const technicalLiteralPatterns = [
  /^\.{0,2}\//,
  /^@/,
  /^#[a-z0-9-]+$/i,
  /^\/[a-z0-9._/-]+$/i,
  /^https?:\/\//,
  /^[a-z]+\/[a-z0-9.+-]+(?:; charset=[a-z0-9-]+)?$/i,
  /^[A-Z0-9_]+$/,
  /^[a-z][a-z0-9]*(?:[A-Z][a-z0-9]*)*$/i,
  /^[a-z][a-z0-9]*(?:\.[a-z][a-z0-9]*)+$/i,
  /^[a-z0-9-]+$/i,
  /^\[[a-z ]+\]$/i,
];

function readSourceFiles(root) {
  const entries = fs.readdirSync(root, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const nextPath = path.join(root, entry.name);

    if (entry.isDirectory()) {
      if (!skippedSegments.has(entry.name)) {
        files.push(...readSourceFiles(nextPath));
      }

      continue;
    }

    if (sourceExtensions.has(path.extname(entry.name))) {
      files.push(nextPath);
    }
  }

  return files;
}

function collectValues(value) {
  if (typeof value === "string") {
    return [value];
  }

  if (Array.isArray(value)) {
    return value.flatMap(collectValues);
  }

  if (value && typeof value === "object") {
    return Object.values(value).flatMap(collectValues);
  }

  return [];
}

function isVisibleLiteral(value) {
  return (
    value.length > 2 &&
    /[A-Za-z]/.test(value) &&
    !/^[a-z0-9-]+$/i.test(value)
  );
}

function getScriptKind(filePath) {
  if (filePath.endsWith(".tsx")) {
    return ts.ScriptKind.TSX;
  }

  if (filePath.endsWith(".ts")) {
    return ts.ScriptKind.TS;
  }

  return ts.ScriptKind.JS;
}

function hasAncestor(node, predicate) {
  let current = node.parent;

  while (current) {
    if (predicate(current)) {
      return true;
    }

    current = current.parent;
  }

  return false;
}

function isNonMessageContext(node) {
  return hasAncestor(
    node,
    (ancestor) =>
      ts.isImportDeclaration(ancestor) ||
      ts.isExportDeclaration(ancestor) ||
      ts.isImportTypeNode(ancestor) ||
      ts.isLiteralTypeNode(ancestor) ||
      ts.isTypeAliasDeclaration(ancestor) ||
      ts.isInterfaceDeclaration(ancestor)
  );
}

function looksLikeCode(value) {
  return (
    /[{};=<>]/.test(value) ||
    /\b(return|export|const|let|function|import|type)\b/.test(value) ||
    /=>/.test(value) ||
    /\/\*/.test(value)
  );
}

function isTechnicalLiteral(value) {
  const normalized = value.trim().replace(/\s+/g, " ");

  return (
    technicalLiteralAllowlist.has(normalized) ||
    looksLikeCode(normalized) ||
    technicalLiteralPatterns.some((pattern) => pattern.test(normalized))
  );
}

function isLikelyUserFacingLiteral(value) {
  const normalized = value.trim().replace(/\s+/g, " ");

  return (
    normalized.length > 2 &&
    /[A-Za-z]/.test(normalized) &&
    !isTechnicalLiteral(normalized) &&
    (/\s/.test(normalized) || /[.!?:]$/.test(normalized))
  );
}

function collectStringLiterals(filePath) {
  const content = fs.readFileSync(filePath, "utf8");
  const sourceFile = ts.createSourceFile(
    filePath,
    content,
    ts.ScriptTarget.Latest,
    true,
    getScriptKind(filePath)
  );
  const literals = [];

  function addLiteral(node, value) {
    if (value && !isNonMessageContext(node) && isLikelyUserFacingLiteral(value)) {
      const line = sourceFile.getLineAndCharacterOfPosition(node.getStart()).line + 1;
      literals.push(`${filePath}:${line}: ${JSON.stringify(value.trim())}`);
    }
  }

  function visit(node) {
    if (ts.isStringLiteral(node) || ts.isNoSubstitutionTemplateLiteral(node)) {
      addLiteral(node, node.text);
    } else if (ts.isTemplateExpression(node)) {
      addLiteral(node, node.head.text);

      for (const span of node.templateSpans) {
        addLiteral(span.literal, span.literal.text);
      }
    }

    ts.forEachChild(node, visit);
  }

  visit(sourceFile);

  return literals;
}

test("likely user-facing message values are not duplicated outside en.json", () => {
  const source = sourceRoots
    .flatMap(readSourceFiles)
    .map((filePath) => ({
      filePath,
      content: fs.readFileSync(filePath, "utf8"),
    }));
  const messageValues = [...new Set(collectValues(messages).filter(isVisibleLiteral))];
  const duplicates = [];

  for (const value of messageValues) {
    for (const { content, filePath } of source) {
      if (content.includes(value)) {
        duplicates.push(`${filePath}: ${JSON.stringify(value)}`);
      }
    }
  }

  assert.deepEqual(duplicates, []);
});

test("likely user-facing string literals live in en.json", () => {
  const literals = sourceRoots
    .flatMap(readSourceFiles)
    .flatMap(collectStringLiterals);

  assert.deepEqual(literals, []);
});
